version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-backend-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/compagnie
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0628970725
    networks:
      - my-network

  frontend:
    build:
      context: ./src/main/webapp/reactjs
      dockerfile: Dockerfile
    image: my-frontend-app
    ports:
      - "3001:80"
    networks:
      - my-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0628970725
      POSTGRES_DB: compagnie
    volumes:
      - /new/path/to/data:/var/lib/postgresql/data
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
